### ISSUE TITLE
DBN-JSON representation for Fortran files without a PROGRAM module

### ISSUE THREAD

**Issue by pratikbhd** [ml4ai/delphi#109]
The current structure of the pgm.json file is as follows:
```
{
"start": <name_of_PROGRAM_module>
"name": "pgm.json"
"dateCreated": <date_of_creation>
"functions": [<list_of_functions>]
}
```
This means that the "start" key is only created when there is a PROGRAM module in the FORTRAN file. Both the PETPT.for and PETASCE.for files do not have a PROGRAM module and only contain SUBROUTINES. For these files, a "start" field is not created and the pgm/lambdas generation script crashes. 

For now, I will add an initial check where a search for this PROGRAM module is made and if not found, a dummy "start" field will be added. Moving forward, how can we represent such FORTRAN files?

**Comment by pauldhein** [comment]
@pratikbhd I like the idea of having a "dummy" start field. For now in the JSON spec lets have this dummy start field be defined as the key of "start" pointing to the JSON `null` value.

**Comment by adarshp** [comment]
I think this is resolved, yes?
