### ISSUE TITLE
Implement functionality to handle multi-level array indexing

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#114]

**Comment by adarshp** [comment]
@skdebray Is this functionality implemented by the Array class?

**Comment by skdebray** [comment]
@adarshp The Array class handles multi-dimensional arrays (e.g., see https://github.com/ml4ai/delphi/blob/master/tests/data/program_analysis/arrays/arrays-basic-06.f).  I assume "multi-level" == "multi-dimensional"?

**Comment by adarshp** [comment]
@skdebray Great! Yes, multi-level = multi-dimensional. I'll marked this as closed by #182 .
