### ISSUE TITLE
Option to specify output location when creating model/dressed CAG

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#13]
@dgarijo: Re: our email conversation - it is possible to set the output path of the result folder while creating the model using the `--model_dir` flag. However, this is probably not so clear from the help message. In any case, I'll add flags to the delphi CLI to specify the separate locations of the output model files.

**Comment by dgarijo** [comment]
Thanks. Does the --output flag specify the name of the file used as output, or is it the path?

**Comment by adarshp** [comment]
It specifies the name of the file. Basically, it's the first argument to the Python built-in function [open()](https://docs.python.org/3/library/functions.html#open).

**Comment by adarshp** [comment]
Closed by 281a0bc3de0a6e7006bdf83d6e2e91fe99f657d8.
