### ISSUE TITLE
where to put for2py test inputs

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#136]
I've been making up tests for various Fortran language constructs for2py will have to handle (currently: I/O and modules; soon: multi-dimensional arrays).  Right now these tests are in a couple of different places: some are in `delphi/tests/data` and some are in `delphi/delphi/program_analysis/autoTranslate/tests/test_data/`.  It would be good for all of these to live in the same place.  Where should I put them?

**Comment by adarshp** [comment]
I think `delphi/tests/data` would be the best place for these - thanks!

**Comment by skdebray** [comment]
OK, thanks.  I've moved them over.
