### ISSUE TITLE
program analysis also in delphi

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/delphi#14]
@adarshp : Posting as "question" for discussion, although I'm "stating" it here...
The program analysis project right now has the following components:
    (1) Analyze fortran to map to python
    (2) Analyze pythons AST to map to CAG with functions that can be input to delphi
    (3) Sensitivity analysis of delphi CAG with functions
Item (3) will be in delphi (has general use).
For now, I'd like to put parts of (2) also in the delphi project, under the directory program_analysis/ (at project root, sibling to sensitivity).  For now I'll keep this in the sensitivity branch.  This means probably adding Jon Stephens to the project.  
Long term: This may move out depending on whether we consider the python side of program analysis a component of delphi (which currently I'm ok with it)

**Comment by adarshp** [comment]
I think this sounds like a good idea. We can keep program analysis-specific package dependencies as optional while they are in flux using the method [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

**Comment by cl4yton** [comment]
I didn't know setup tools could do that (I have used them much, but this is cool).
I think the program-analysis-specific work, focusing on translating from python.AST to export delphi_DBN json should be *very* lightweight -- it really should only need pure python.
Sensitivity, however, will include tangent (https://github.com/google/tangent) -- when I get to that.

**Comment by adarshp** [comment]
Awesome, less messing around with the arcana of setuptools = more happiness for me :)
