### ISSUE TITLE
deliverables for Jan 2019

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#144]
As discussed last week, the deliverables for Jan 2019 include: 

- 1.1a: Progress on handling multi-level array indexing and open-ended loops (while); and
- 1.2a: Progress on automatic differentiation and Bayesian optimization for one DSSAT module.

Both arrays and modules have tons of features, and we'll have time to handle only some of them.  Given this, it may be useful for us to discuss and come to agreement on which specific features of arrays (1.1a) and modules (1.2a) we should aim to handle for this deliverable.  I propose the following:

- arrays: [this program](https://github.com/ml4ai/delphi/blob/master/tests/data/arrays/arrays-basic-08.f) to solve a set of linear equations using Gaussian elimination.
- modules: [this program](https://github.com/ml4ai/delphi/blob/master/tests/data/modules/PETASCE_01.for) and [this program](https://github.com/ml4ai/delphi/blob/master/tests/data/modules/PETASCE_02.for) (PETASCE.for with baby modules)

Thoughts?

**Comment by adarshp** [comment]
@skdebray - we do have some breathing room for tasks 1.1a and 1.2a (8 and 10 months respectively) - but I think it's a good idea to start thinking about them early. I'm by no means a Fortran expert, but I think the programs you proposed to analyze look good, and would serve as nice demonstrations of PA capabilities.

**Comment by skdebray** [comment]
@adarshp I agree that tasks 1.1 and 1.2 are supposed to be _completed_ by months 8 and 10; my impression is that by the end of Jan 2019 we're supposed to "demonstrate progress" on them.  I'm simply trying to get to agreement on what specific examples we use to demonstrate progress.

Part of the issue here is that  as we begin to tackle a bigger variety of source language constructs in for2py there will likely be an impact on downstream analyses, and it's possible that some of those impacts may then ripple back and require nontrivial changes in existing for2py code (see example below).  To the extent that we can agree on and plan for those things, it'll make our lives a slight bit easier.

Example [modules]: The GrFN spec currently considers single-file programs.  When we go to programs with multiple modules, we'll have to deal with multi-file programs (this is necessary since some of our milestones involve doing things like analyzing different modules in parallel).  To me, it seems natural that the GrFN specs for independent program units should be generated independently.  But if that's the case, then we have to make sure that if a program A uses modules B and C, then there are no inadvertent collisions between variable names in the (independently generated) GrFN specs GrFN_A, GrFN_B, and GrFN_C.  If this is going to be handled in the delphi front-end, that's fine; but if it's going to be handled in the for2py code that generates the GrFN specs, then it would be helpful to understand and plan for the changes that might be necessary to existing code in for2py --- especially if we plan to demonstrate progress on handling modules by the end of January.

@cl4yton : what do you think?

**Comment by skdebray** [comment]
I think we're on track with nailing down the specifics for this issue so I'll go ahead and close it.

**Comment by adarshp** [comment]
@skdebray Great, thanks!

**Comment by cl4yton** [comment]
@skdebray Thanks for this discussion, and apologies for not jumping in here -- it's precisely the right venue for this kind of concern/discussion, esp. to initiate. And I agree, we do appear to be on track to nailing down the specifics, both on the for2py and the GrFN side. Thanks!
