### ISSUE TITLE
indra and networkx version

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/delphi#15]
While creating a fresh virtual env for delphi development using requirements, I noticed this was generated:
indra 1.7.0 has requirement networkx==1.11, but you'll have networkx 2.1 which is incompatible.
Is this a concern?

**Comment by adarshp** [comment]
No, it won't be a problem. The NetworkX-specific functionality of Delphi has been implemented for NetworkX 2.1. INDRA is in the process of migrating to NetworkX 2.1 (https://github.com/sorgerlab/indra/pull/404) but Delphi doesn't use any of the INDRA modules that depend on NetworkX 1.11.

**Comment by adarshp** [comment]
However, this is a good point - I don't if there is a way for `setuptools` to ignore specific versions for specific package sub-dependencies.
