### ISSUE TITLE
Type misnaming in generated GrFN JSON

### ISSUE THREAD

**Issue by pauldhein** [ml4ai/delphi#166]
Functions in the GrFN JSON that are `condition`s or `decision`s should have their types labeled as such. Currently our `pgm.json` for `crop_yield.f` has the following function definitions:
```json
{
      "name": "UPDATE_EST__condition__IF_1_0",
      "type": "assign",
},
...
{
      "name": "UPDATE_EST__decision__YIELD_EST_0",
      "type": "assign",
},
```

We need to change these definitions to the following:
```json
{
      "name": "UPDATE_EST__condition__IF_1_0",
      "type": "condition",
},
...
{
      "name": "UPDATE_EST__decision__YIELD_EST_0",
      "type": "decision",
},
```
The `for2py` module should be updated to reflect this change so that future `condition`s and `decision`s are identified with their types properly as opposed to being identifier with `assign`.

**Comment by hlim1** [comment]
@pauldhein I fixed the issue in the genPGM.py and ran the test. The output shows the correct type names with "condition" and "decision". I just requested the issue_#166 branch that has a fix to be merged with the master.

**Comment by skdebray** [comment]
@pauldhein let me know if anything further needs to be done for this.  If not I'll go ahead and close this issue.

**Comment by pauldhein** [comment]
This issue is ready to be closed
