### ISSUE TITLE
Travis test failing

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#167]
@pratikbhd One of the changes introduced in #165 seems to make the automated test suit fail (https://travis-ci.org/ml4ai/delphi/builds/487867022) - could you please submit a PR that fixes it?

**Comment by skdebray** [comment]
@adarshp If you're satisfied with the fix I'll go ahead and close this issue.

**Comment by adarshp** [comment]
Yes, I am! I'll close it now.

Closed by #168 .
