### ISSUE TITLE
Missing Lambdas for __decision__ nodes

### ISSUE THREAD

**Issue by pauldhein** [ml4ai/delphi#185]
Consider the following snippet of code from `PETPT.for`:

```fortran
IF (XHLAI .LE. 0.0) THEN
    ALBEDO = MSALB
ELSE
    ALBEDO = 0.23-(0.23-MSALB)*EXP(-0.75*XHLAI)
ENDIF
```

In our `grfn.json` file we get the following functions from this code:
```json
{
      "name": "petpt__condition__IF_1_0",
      "type": "condition",
      "target": "IF_1",
      "sources": [
        {
          "name": "xhlai",
          "type": "variable"
        }
      ],
      "body": [
        {
          "type": "lambda",
          "name": "petpt__lambda__IF_1_0",
          "reference": 17
        }
      ]
    },
    {
      "name": "petpt__assign__albedo_0",
      "type": "assign",
      "sources": [
        {
          "name": "msalb",
          "type": "variable"
        }
      ],
      "body": [
        {
          "type": "lambda",
          "name": "petpt__lambda__albedo_0",
          "reference": 18
        }
      ],
      "target": "albedo"
    },
    {
      "name": "petpt__assign__albedo_1",
      "type": "assign",
      "sources": [
        {
          "name": "msalb",
          "type": "variable"
        },
        {
          "name": "math.exp",
          "type": "function"
        }
      ],
      "body": [
        {
          "type": "lambda",
          "name": "petpt__lambda__albedo_1",
          "reference": 20
        }
      ],
      "target": "albedo"
    },
    {
      "name": "petpt__decision__msalb_0",
      "type": "decision",
      "target": "msalb",
      "sources": [
        {
          "name": "IF_1_0",
          "type": "variable"
        },
        {
          "name": "msalb_0",
          "type": "variable"
        },
        {
          "name": "msalb_0",
          "type": "variable"
        }
      ]
    },
    {
      "name": "petpt__decision__albedo_0",
      "type": "decision",
      "target": "albedo",
      "sources": [
        {
          "name": "IF_1_0",
          "type": "variable"
        },
        {
          "name": "albedo_3",
          "type": "variable"
        },
        {
          "name": "albedo_2",
          "type": "variable"
        }
      ]
    },
```
A couple necessary corrections:
1. `petpt__decision__msalb_0` should not have been generated. This needs to be removed.
2. `petpt__decision__albedo_0` should probably be renamed, such that the ending `albedo` has the index of the actual `albedo` that we are assigning (in this case, index 2).
3. The `albedo` variables being sent in to `petpt__decision__albedo_0` have incorrect indices (should be 0 and 1, but we are sending in 2 and 3).

Now for the meat and potatoes ... we have well defined lambdas in `PETPT_lambdas.py` for both `petpt__assign__albedo_0` and `petpt__assign__albedo_1`, but no such lambda is generated for `petpt__decision__albedo_0`. Here is my proposal of what this lambda should look like:
```python
def petpt__lambda__albedo_0(msalb):
    return msalb

def petpt__lambda__albedo_1(msalb):
    return (0.23-((0.23-msalb)*math.exp(-((0.75*xhlai)))))

def petpt__lambda__albedo_2(IF_1_0, albedo_0, albedo_1):
    return albedo_0 if IF_1_0 else albedo_1
```
As you see the new lambda takes in the conditional evaluation variable `IF_1_0`, the two possible assignment variables, `albedo_0` and `albedo_1`, and then performs the if/else to return the proper assignment. Can we add the generation of this lambda to `genPGM.py`?

**Comment by pratikbhd** [comment]
@pauldhein I am implementing the corrections you mentioned in the comment above and want to be sure of something before I go ahead with the changes.
For point 3, I see that having the indices of the `albedo` variable to be 0 and 1 (instead of 2 and 3) helps in pointing to the `__assign__` instances of the this variable which makes sense to do. However, the `decision` tags for variable `EO` are quite different since it has an `IF-ELSE-IF` block.
This change requires restructuring the code that will have to be general for all `decision` tags in the program so it would help me if you could give an example for how you want the `decision` tags of the `EO` variable to look like in the `PETPT.for` program.

**Comment by pauldhein** [comment]
Closed by #199

**Comment by pauldhein** [comment]
@pratikbhd I see your point from #200. The way I suggested to handle `__decision__` nodes is not gonna generalize to an `if` with an `elif`, without an `else` and furthermore it won't generalize to if blocks that have multiple lines container under the `if`. We will need to think about how to handle this, but I'm thinking that for now what you are generating in `PETPT_lambdas.py` will work. Namely, take each if in the `if-elif` and add the value that `EO` would be otherwise as the implicit else. Does that work for you?

**Comment by pratikbhd** [comment]
@pauldhein Currently, there are two decision blocks for `EO` generated in `PETPT_lambdas.py` as follows:
```
        {
          "name": "petpt__decision__eo_3",
          "output": {
            "variable": "eo",
            "index": 4
          },
          "input": [
            {
              "variable": "IF_3",
              "index": 0
            },
            {
              "variable": "eo",
              "index": 1
            },
            {
              "variable": "eo",
              "index": 3
            }
          ]
        },
        {
          "name": "petpt__decision__eo_3",
          "output": {
            "variable": "eo",
            "index": 5
          },
          "input": [
            {
              "variable": "IF_2",
              "index": 0
            },
            {
              "variable": "eo",
              "index": 4
            },
            {
              "variable": "eo",
              "index": 2
            }
          ]
        }
```
Both these decision blocks have the same index `3` and the index for different instances of `EO` seem weird. This is the same issue as that was pointed out in point 3 of your comment above. I think the following representation would make more sense:
```
        {
          "name": "petpt__decision__eo_3",
          "output": {
            "variable": "eo",
            "index": 3
          },
          "input": [
            {
              "variable": "IF_2",
              "index": 0
            },
            {
              "variable": "eo",
              "index": 1
            },
            {
              "variable": "decision__eo",
              "index": 4
            }
          ]
        },
        {
          "name": "petpt__decision__eo_4",
          "output": {
            "variable": "eo",
            "index": 4
          },
          "input": [
            {
              "variable": "IF_3",
              "index": 0
            },
            {
              "variable": "eo",
              "index": 2
            },
          ]
        }
```
Is this something that makes the representation more meaningful for further work with the lambda and gfrn json or is the first representation good enough?

**Comment by pauldhein** [comment]
@pratikbhd I do see the initial problem that you were worried about now. I agree that for now your solution of having the `__decision__` index match the `eo` index seems to work. Please add that to the #200 PR and we will revisit the naming issue of `__decision__` nodes at a later date. Close this issue once the changes have been made.
