### ISSUE TITLE
More bugs in GrFN JSON and lambdas.py

### ISSUE THREAD

**Issue by pauldhein** [ml4ai/delphi#187]
Lets take another look at `PETPT.for`:
```fortran
IF (XHLAI .LE. 0.0) THEN
  ALBEDO = MSALB
ELSE
  ALBEDO = 0.23-(0.23-MSALB)*EXP(-0.75*XHLAI)   ! <-- Line of interest
ENDIF
```
Our line of interest denotes that `albedo` is being assigned as dependent upon `msalb` and `xhlai`. However, I found the following was generated as a lambda function for this expression:
```python
def petpt__lambda__albedo_1(msalb):
    return (0.23-((0.23-msalb)*math.exp(-((0.75*xhlai)))))
```
As you see we are missing an argument, `xhlai`, which should be added to the generated lambda. This convinced me to take a look at the GrFN spec to see if the variable is being correctly recorded as an input. Here is what I found:
```json
{
  "name": "petpt__assign__albedo_1",
  "type": "assign",
  "sources": [
    {
      "name": "msalb",
      "type": "variable"
    },
    {
      "name": "math.exp",
      "type": "function"
    }
  ],
  "body": [
    {
      "type": "lambda",
      "name": "petpt__lambda__albedo_1",
      "reference": 20
    }
  ],
  "target": "albedo"
},
```
So it looks like there are two problems with the GrFN source for this assignment.
1. We are missing `xhlai` as a source in the `sources` list
2. We should not be passing functions (such as `math.exp`) as arguments into functions

So why is (2) present as a problem but not reflected as a problem in the `lambdas.py` file? Well I decided to investigate the JSON in the `body` of the `petpt` container function, and this is what I found:
```json
{
  "name": "petpt",
  "type": "container",
  "body": [
    {
      "name": "petpt__assign__albedo_1",
      "output": {
         "variable": "albedo",
         "index": 3
      },
      "input": [
        {
          "variable": "msalb",
          "index": 0
        }
      ]
    },
  ]
}
```
So it looks like the `math.exp` function variable is not appearing when the assignment statement is part of the body of a container function. This is good, but we will want to be consistent and update the actual assignment function body to have the same source list. Also to recap, we will need to add `xhlai` to both of these lists.

**Comment by adarshp** [comment]
Closed by #188  and #189
