### ISSUE TITLE
More PETPT variable ordering discrepancies

### ISSUE THREAD

**Issue by pauldhein** [ml4ai/delphi#207]
I am still finding source orderings mismatches between the generated lambdas and the JSON for the PETPT program. Here is the latest example:
```python
def petpt__assign__eeq_1(albedo, td, slang):
    return ((slang*(0.000204-(0.000183*albedo)))*(td+29.0))
```

```json
{
  "name": "petpt__assign__eeq_1",
  "output": {
    "variable": "eeq",
    "index": 1
  },
  "input": [
    {
      "variable": "slang",
      "index": 1
    },
    {
      "variable": "albedo",
      "index": 3
    },
    {
      "variable": "td",
      "index": 1
    }
  ]
},
```

@pratikbhd I need these to be corrected.

**Comment by pratikbhd** [comment]
@pauldhein I am not seeing this issue replicating when I run the code in the `master` branch.

<img width="1444" alt="Screen Shot 2019-03-09 at 3 44 57 PM" src="https://user-images.githubusercontent.com/19292952/54078265-8ec57e00-4282-11e9-9384-b972160f1fff.png">

**Comment by pauldhein** [comment]
It was discovered that this was an issue with my own branch. I was using an out-of-date lambdas file. Thank you @pratikbhd for clearing this up!
