### ISSUE TITLE
bug in rectify.py

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#249]
The code for AST fixup (`rectify.py`) does not correctly handle user-defined functions in the Fortran source.  For example, given the following program:
```
      integer function foo(x)
      implicit none
      integer x
      foo = x + 1234567      ! return value of the function
      end function foo

      program main
      integer u, foo
      u = foo(3)
 10   format(I8)
      write (*,10) u
      end program main
```
the output from `rectify.py` has only the following line for the function `foo()`, i.e., the body of `foo()` is missing:
```
    <function name="foo" />
```
and `grep 123456 <rectified-file-name>` is empty.

**Comment by hlim1** [comment]
I've fixed the issue and made a pull request.
The fix was made in both rectify.py and pyTranslate.py.

**Comment by hlim1** [comment]
Bug has been fixed. Closing this issue.
