### ISSUE TITLE
fix the external interface to rectify.py

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#273]
The external interface to the file `rectify.py` has some significant problems that need to be fixed:

1) There are currently two ways to rectify an XML file: (1) we can call `buildNewAST()` with a file name, or (2) we can call `buildNewASTfromXMLString()` with an XML string.  There is a LOT of code duplication between these functions.  This needs to be fixed.  

2) The function `buildNewAST()` has hard-wired assumptions about the name and location of the output file.  This is bad for all kinds of reasons and needs to be fixed.  

3) The current code optimistically assumes that the input and output file operations won't run into problems -- e.g., that the input file exists and is readable, the output file is writable, etc.  While optimism is often admirable, it isn't so great when it comes to programming --- please write defensive code.  This needs to be fixed.

4) `__main__()` optimistically assumes that the user will provide an argument.  See above about optimism.

I request the following structure:

  - Have _a single_ function `buildNewASTfromXMLString()` that takes as argument an input XML string and which returns a rectified AST.  This is the _only_ code that does rectification; it will be the interface used by the testing code.
 - Have `buildNewAST()` take two file names: an input file name and an output file name.  It should read an XML string from the input file, pass that string to `buildNewASTfromXMLString()`, and write the value returned to the output file specified.
 - Have `__main__()` invoke `buildNewAST()` with the appropriate arguments.  (See comment above about optimism.)
 - Use `try-except` constructs to guard your file operations.

Please fix the code to address these problems before going further.

**Comment by hlim1** [comment]
These issues were on the discussion process with Adarsh while we were troubleshooting the pyTest issue. Adarsh, also, mentioned that one of the reasons may be due to the duplication of the code that one is for autoTranslate and another is for pyTest. Therefore, I was working on to remove these duplications and have a single function to be called by both files. I was working on this fix in the goto_elimination branch, but since there is a more clear set of instructions that you provided, I will continue this fix in the new branch and do a PR as soon as it is done. Thank you.

**Comment by hlim1** [comment]
@skdebray I've just made a PR for issue_273 branch, which holds the fixes for this issue. In that PR, I also fixed the goto_elimination pyTest failing error, which increased the code coverage to 66.01%. Please do review the PR and provide me with feedback if any further fix is needed or I missed anything to address from your request. There may be more duplicate codes in the rectify.py that I have missed to address. For those cases, I will watch out while I handle goto_elimination and remove them unless they cause a serious bug. Then, I will create a separate branch and address them immediately.

**Comment by skdebray** [comment]
The code has been revised as requested.
