### ISSUE TITLE
rectify.py bug: expressions in output lists

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#289]
The following Fortran program gives rise to an assertion failure in `rectify.py`:

```
      program main
      implicit none
      integer x
      x = 20
      write (*, 10) x*10
 10   format(I4)
      stop
      end program main
```

**Comment by hlim1** [comment]
@skdebray I just requested a PR for this issue. Having an operation is a new case, but a simple tag addition to the list solved the case. As you said, having these lists are convenient. I will replace any individual tag checking if-statement with the list checking as I code further.
