### ISSUE TITLE
GrFN loop issue

### ISSUE THREAD

**Issue by hlim1** [ml4ai/delphi#337]
The GrFN generation halts due to assert fail in `genPGM.py` while handling a loop.
Error: `assert "boolean_operation" in loop_test[0][0], f"Invalid loop " \`

Tested code:
```
      program main
      implicit none

      integer :: Tmax = 100
      integer i, j

      j = 0
      i = 0
      do while (i < Tmax)
          j = j + 1
          i = i + 1
      end do

      end program main
```

**Comment by pratikbhd** [comment]
The fix for this issue has been implemented and pushed in `SIR-demo` which will be merged into master through #344
