### ISSUE TITLE
Kill json_dev branch

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/delphi#35]
@adarshp : I'd like to kill the json_dev branch.  Rather than merge with master (which is far ahead), I'm going to create a new branch called pa_dev which will be for program analysis.  But before I go ahead an kill json_dev, just wanted to run by you.

**Comment by cl4yton** [comment]
I should have presented a little more detail about rational: there's nothing currently in json_dev branch worth keeping due to changes in thinking and rapid revisions; so fresh start in new branch makes sense to me.

**Comment by adarshp** [comment]
Fine with me!

**Comment by cl4yton** [comment]
Done!
