### ISSUE TITLE
Error in installing delphi: unknown type name 'NEIGHBOR_ITERATOR'

### ISSUE THREAD

**Issue by phosseini** [ml4ai/delphi#353]
I have some trouble installing delphi on my system. I think the following log is the best way to describe my problem. Just a few things:

My system info: **macOS Mojave Version 10.14.6**

It's pretty much obvious to me that there's something wrong with the cpp compilation part. However, I still couldn't figure out what to do to solve the issue. I compiled the delphi folder using CMake and here is the log after running `cmake`:

`
[ 28%] Building CXX object CMakeFiles/Delphi.dir/lib/AnalysisGraph.cpp.o
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:1:
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.hpp:11:
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:167:14: error: no template named '_Rb_tree_const_iterator' in namespace 'std'; did you mean '__tree_const_iterator'?
        std::_Rb_tree_const_iterator<boost::detail::stored_edge_iter<
        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
             __tree_const_iterator
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:868:70: note: '__tree_const_iterator' declared here
    template <class, class, class> friend class _LIBCPP_TEMPLATE_VIS __tree_const_iterator;
                                                                     ^
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:1:
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.hpp:11:
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:169:18: error: no template named '_List_iterator' in namespace 'std'; did you mean '__list_iterator'?
            std::_List_iterator<boost::list_edge<long unsigned int, Edge>>,
            ~~~~~^~~~~~~~~~~~~~
                 __list_iterator
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/list:281:28: note: '__list_iterator' declared here
class _LIBCPP_TEMPLATE_VIS __list_iterator
                           ^
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:1:
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.hpp:11:
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:169:18: error: too few template arguments for class template '__list_iterator'
            std::_List_iterator<boost::list_edge<long unsigned int, Edge>>,
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/list:281:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS __list_iterator
                           ^
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:1:
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.hpp:11:
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:173:57: error: expected a type
                                      long unsigned int>,
                                                        ^
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:174:18: error: expected a type
        long int>,
                 ^
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:176:22: error: expected a type
    NEIGHBOR_ITERATOR;
                     ^
/Users/phosseini/Resources/delphi/lib/DiGraph.hpp:176:22: error: expected a type
In file included from /Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:1:
/Users/phosseini/Resources/delphi/lib/AnalysisGraph.hpp:57:3: error: unknown type name 'NEIGHBOR_ITERATOR'
  NEIGHBOR_ITERATOR successors(int i);
  ^
/Users/phosseini/Resources/delphi/lib/AnalysisGraph.hpp:171:26: error: unknown type name 'NEIGHBOR_ITERATOR'
                         NEIGHBOR_ITERATOR (AnalysisGraph::*neighbors)(int));
                         ^
/Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:33:1: error: unknown type name 'NEIGHBOR_ITERATOR'
NEIGHBOR_ITERATOR AnalysisGraph::successors(int i) {
^
/Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:34:10: error: no viable conversion from returned value of type 'iterator_range<typename range_iterator<const pair<adjacency_iterator<adjacency_list<setS, vecS, bidirectionalS, Node, Edge, GraphData, listS>, unsigned
      long, out_edge_iter<__tree_const_iterator<stored_edge_iter<unsigned long, __list_iterator<list_edge<unsigned long, Edge>, void *>, Edge>, __tree_node<stored_edge_iter<unsigned long, __list_iterator<list_edge<unsigned long, Edge>, void *>, Edge>, void *> *, long>,
      unsigned long, edge_desc_impl<bidirectional_tag, unsigned long>, long>, long>, adjacency_iterator<adjacency_list<setS, vecS, bidirectionalS, Node, Edge, GraphData, listS>, unsigned long, out_edge_iter<__tree_const_iterator<stored_edge_iter<unsigned long,
      __list_iterator<list_edge<unsigned long, Edge>, void *>, Edge>, __tree_node<stored_edge_iter<unsigned long, __list_iterator<list_edge<unsigned long, Edge>, void *>, Edge>, void *> *, long>, unsigned long, edge_desc_impl<bidirectional_tag, unsigned long>, long>,
      long> > >::type>' (aka 'iterator_range<boost::adjacency_iterator<boost::adjacency_list<boost::setS, boost::vecS, boost::bidirectionalS, Node, Edge, GraphData, boost::listS>, unsigned long,
      boost::detail::out_edge_iter<std::__1::__tree_const_iterator<boost::detail::stored_edge_iter<unsigned long, std::__1::__list_iterator<boost::list_edge<unsigned long, Edge>, void *>, Edge>, std::__1::__tree_node<boost::detail::stored_edge_iter<unsigned long,
      std::__1::__list_iterator<boost::list_edge<unsigned long, Edge>, void *>, Edge>, void *> *, long>, unsigned long, boost::detail::edge_desc_impl<boost::bidirectional_tag, unsigned long>, long>, long> >') to function return type 'int'
  return make_iterator_range(boost::adjacent_vertices(i, this->graph));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/boost/range/iterator_range_core.hpp:237:5: note: candidate function
    operator unspecified_bool_type() const
    ^
/Users/phosseini/Resources/delphi/lib/AnalysisGraph.cpp:188:5: error: unknown type name 'NEIGHBOR_ITERATOR'
    NEIGHBOR_ITERATOR (AnalysisGraph::*neighbors)(int)) {
    ^
12 errors generated.
make[2]: *** [CMakeFiles/Delphi.dir/build.make:63: CMakeFiles/Delphi.dir/lib/AnalysisGraph.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:178: CMakeFiles/Delphi.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by adarshp** [comment]
It looks like you are compiling using AppleClang - we have tested Delphi with GCC 8 and 9, but AppleClang does not work - there are some C++17 features that are not yet supported with the latest stable release of XCode. Try installing gcc 8 or 9 using Homebrew or MacPorts and trying that?

**Comment by phosseini** [comment]
> It looks like you are compiling using AppleClang - we have tested Delphi with GCC 8 and 9, but AppleClang does not work - there are some C++17 features that are not yet supported with the latest stable release of XCode. Try installing gcc 8 or 9 using Homebrew or MacPorts and trying that?

I see, I have gcc 9 installed, then the question is how can I use gcc as the default compiler when installing delphi?

**Comment by adarshp** [comment]
> [

One thing that you could try is to set the `CC` and `CXX` environment variables to the locations of the `gcc` and `g++` binaries you want to use. Did you install gcc using Homebrew, MacPorts, or another method?

**Comment by phosseini** [comment]
> > [
> 
> One thing that you could try is to set the `CC` and `CXX` environment variables to the locations of the `gcc` and `g++` binaries you want to use. Did you install gcc using Homebrew, MacPorts, or another method?

I installed gcc using Homebrew and also corrected the links. Now that I type gcc --version in my command line I see the following:
`gcc --version
gcc-9 (Homebrew GCC 9.2.0) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

So I think the gcc is properly linked. But I still get the error.

**Comment by adarshp** [comment]
> > > [
> > 
> > 
> > One thing that you could try is to set the `CC` and `CXX` environment variables to the locations of the `gcc` and `g++` binaries you want to use. Did you install gcc using Homebrew, MacPorts, or another method?
> 
> I installed gcc using Homebrew and also corrected the links. Now that I type `gcc --version` in my command line, I see the following:
> `gcc --version gcc-9 (Homebrew GCC 9.2.0) 9.2.0 Copyright (C) 2019 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`
> 
> So I think the gcc is properly linked. But I still get the error.

Can you post the output of the `cmake` command? That should tell you which compiler is being used.

> 
> P.S. what do you mean on your website by `Delphi has been tested with **Clang 8** and G++ 8.` if Clang doesn't work?

Sorry, that is a bit out of date - Clang is not supported as of now, perhaps when Apple releases the new Xcode version.

**Comment by phosseini** [comment]
I did set the `CC` and `CXX` compilers to the absolute path of gcc and g++ compilers' binaries and cmake **IS** using these two compilers now. However, after running `make` I get the following error:

```
[ 14%] Built target fmt
[ 23%] Built target spdlog
[ 71%] Built target Delphi
[ 76%] Building CXX object CMakeFiles/cpptests.dir/tests/cpptests.cpp.o
In file included from /usr/include/sys/sysctl.h:83:0,
                 from /Users/phosseini/Resources/delphi/external/doctest/doctest.h:2817,
                 from /Users/phosseini/Resources/delphi/tests/cpptests.cpp:3:
/usr/include/sys/ucred.h:94:2: error: ‘_Atomic’ does not name a type
  _Atomic u_long          cr_ref;  /* reference count */
  ^~~~~~~
make[2]: *** [CMakeFiles/cpptests.dir/build.make:63: CMakeFiles/cpptests.dir/tests/cpptests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:92: CMakeFiles/cpptests.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
I've been searching for some solution for this error, I tried [this one](https://apple.stackexchange.com/questions/355049/compilation-error-with-mojave-error-atomic-does-not-name-a-type/355103), but it didn't resolve the issue.

**Comment by adarshp** [comment]
> -- The C compiler identification is GNU 9.2.0
> -- The CXX compiler identification is GNU 7.4.0

There is a discrepancy in the compilers being reported - the first line has 9.2.0 while the second has 7.4.0 - they should be the same version.

Also, I see that you have Boost 1.71 headers in `/opt/local/include`, which makes me think that you installed Boost using MacPorts (I have the same installation). Is that correct? If so, I would advise you that in general it's not a good idea to simultaneously use the Homebrew and MacPorts package managers...if you are not using MacPorts and Homebrew simultaneously, ignore this sentence :)

**Comment by phosseini** [comment]
> > -- The C compiler identification is GNU 9.2.0
> > -- The CXX compiler identification is GNU 7.4.0
> 
> There is a discrepancy in the compilers being reported - the first line has 9.2.0 while the second has 7.4.0 - they should be the same version.
> 
> Also, I see that you have Boost 1.71 headers in `/opt/local/include`, which makes me think that you installed Boost using MacPorts (I have the same installation). Is that correct? If so, I would advise you that in general it's not a good idea to simultaneously use the Homebrew and MacPorts package managers...if you are not using MacPorts and Homebrew simultaneously, ignore this sentence :)

Thanks for all the feedback. I could finally build the project successfully. For future use and those who face the same issue, you have to make sure you're using the proper CC and CXX compilers. In particular and in my case, I set the environment variables in my bash profile file to make it clear for `cmake` what compilers to use:

```
export CC=/usr/local/Cellar/gcc/9.2.0/bin/gcc-9
export CXX=/usr/local/Cellar/gcc/9.2.0/bin/g++-9
```

I can now import the delphi successfully in my project/jupyter notebook, however, when I'm trying to run the example, I get the following error:
```
Invalid instance of 'java/lang/Object' passed for a 'org/clulab/wm/eidos/EidosComponents'
```
I have used `sbt assembly` to generate the huge JAR file for Eidos, but I don't have any idea what causes such error?

**Comment by adarshp** [comment]
> I have used `sbt assembly` to generate the huge JAR file for Eidos, but I don't have any idea what causes such error?

Hm, this is more on the INDRA and Eidos side so I'm not sure if I'll be able to fully figure it out - but I have some ideas.

1. Did you follow the instructions [here](https://indra.readthedocs.io/en/latest/modules/sources/eidos/index.html) to set up the INDRA-Eidos connection?
2. What version of Java do you have? Java 8 / OpenJDK 8 is required for Eidos.

**Comment by phosseini** [comment]
> > I have used `sbt assembly` to generate the huge JAR file for Eidos, but I don't have any idea what causes such error?
> 
> Hm, this is more on the INDRA and Eidos side so I'm not sure if I'll be able to fully figure it out - but I have some ideas.
> 
> 1. Did you follow the instructions [here](https://indra.readthedocs.io/en/latest/modules/sources/eidos/index.html) to set up the INDRA-Eidos connection?
> 2. What version of Java do you have? Java 8 / OpenJDK 8 is required for Eidos.

I see, thanks for all the help, I'll figure it out. I'm closing this since the build issue is resolved.
