### ISSUE TITLE
KeyError: 'duration'

### ISSUE THREAD

**Issue by phosseini** [ml4ai/delphi#370]
I'm trying to run the following example in my jupyter notebook:

```
from delphi.AnalysisGraph import AnalysisGraph
from delphi.visualization import visualize

text = "Significantly increased conflict seen in South Sudan forced many families to flee in 2017."
G = AnalysisGraph.from_text(text, webservice="http://localhost:9000")
visualize(G)
```

and I keep getting the following error which is apparently related to the api that processes eidos's json output (I also created an [issue](https://github.com/clulab/eidos/issues/686) on delphi's repository on this):

```
~/anaconda3/envs/delphi/lib/python3.7/site-packages/indra/sources/eidos/processor.py in time_context_from_timex(timex)
    417     start = _get_time_stamp(constraint.get('start'))
    418     end = _get_time_stamp(constraint.get('end'))
--> 419     duration = constraint['duration']
    420     tc = TimeContext(text=time_text, start=start, end=end,
    421                      duration=duration)

KeyError: 'duration'
```

And interestingly, when I remove **2017** from the input text, then it works! I wonder why this is happening?

Also when I run the very code using another input text which is a bit longer, I get the following error:

> text = "How worried should Washington be that the two nations deemed to be most threatening to the United States’ future are getting close? Perhaps less than some fearmongers think. The truth is, neither Xi nor Putin is starry-eyed about their bromance—nor can they afford to be. Great powers do not mate for life, and that’s especially true of China. The biggest reason for Russia and China to bond now is that each has a tense, unpredictable, and potentially antagonistic relationship with the Trump administration. And ever since the birth of the People’s Republic of China 70 years ago, the triangular dynamic among China, the United States, and Russia (or the then-Soviet Union) has hugely influenced Chinese foreign policy. During the late ’50s and early ’60s, a rancorous Chinese-Soviet split and Moscow’s warming to Washington prompted Mao to host U.S. President Richard Nixon in China. Nixon’s startling 1972 China trip ushered in years of strengthening ties, and even Chinese-U.S. cooperation on efforts to thwart the Soviet occupation of Afghanistan. Moscow and Beijing officially ended their estrangement in 1989. Yet just a few years later, the Soviet collapse led Russian leaders to flirt with the idea of integrating with the West."

```
~/anaconda3/envs/delphi/lib/python3.7/site-packages/delphi/assembly.py in deltas(s)
     11 
     12 def deltas(s: Influence) -> Tuple[Delta, Delta]:
---> 13     return s.subj.delta, s.subj.delta
     14 
     15 

AttributeError: 'Event' object has no attribute 'subj'
```

When I run the very examples in eidos webapp I get no error. So I think the problem is in `processor.py` which includes the api methods for processing eidos's output. I wonder how this problem can be fixed or if you plan to update these api methods accordingly?

**Comment by adarshp** [comment]
Hi @phosseini,

I've pushed a fix for the issue with the longer input text in #371 - I'll merge it into master after tests pass.

As for the 'duration' KeyError, that is something on INDRA side - I recommend posting an issue there (and I'll tag @bgyori here for good measure as well so he is aware)

**Comment by bgyori** [comment]
No issue on the INDRA side, needs to update local version.

**Comment by adarshp** [comment]
> No issue on the INDRA side, needs to update local version.

Got it, thanks @bgyori !
