### ISSUE TITLE
Add line numbers to DBN-JSON in program_analysis_kickoff_demo

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/delphi#41]
I've already found need to refer to parts of the example DBN-JSON in the program_analysis_kickoff_demo jupyter notebook.  Is it possible to add line numbers?

**Comment by adarshp** [comment]
Yes, I think I can do this.

**Comment by adarshp** [comment]
Implemented in 68d48a75168b3622407361bdcd14cec3be5d44f6.

**Comment by adarshp** [comment]
You can call the `delphi/program_analysis/convert.sh` script to convert the notebook with nice scrollable outputs.
