### ISSUE TITLE
Request to change contents of "input" attribute of loop_plate specification

### ISSUE THREAD

**Issue by cl4yton** [ml4ai/delphi#45]
(Just realized I should have first created this as an issue!)

@stephensj2 : @pauldhein is making good progress getting the DBN-JSON to DBN graph wiring working.  Paul identified a change in the DBN-JSON output that we'd like to ask you to make -- this is just for the loop_plate specification.  Up to this point, my thought was that the "input" attribute of the loop_place spec should list all of the variables that are referenced within the loop_plate.  It turns out, it is much more useful to Paul to have this be the list of variable names that are set in the scope (container fn) that the loop_plate appears within.  And in this case, we don't need actual <veriable_reference>s (no need for the index info), just the <variable_name> (the base string name of the variable).  I've update the description of the Function Loop Place Specification to reflect this (text in maroon).

Is it easy for you to make this change?

**Comment by adarshp** [comment]
@stephensj2 Please remember to review #47 (and merge it if necessary) before implementing this!

**Comment by cl4yton** [comment]
Looks like Paul actually has the info he needs, so I will close this and only reopen if necessary
