### ISSUE TITLE
Cannot get saved GrFN JSON from PA team

### ISSUE THREAD

**Issue by pauldhein** [ml4ai/delphi#452]
## Problem
Once again, it seems that the `save_file` functionality to get the GrFN_JSON object created by the PA team has gone missing in the master branch.

#### Additional context
- It seems that `f2grfn.fortran_to_grfn` now has a `save_intermediate_files` variable that can be set to true. However, when setting that to true the only file **not being saved** is the GrFN JSON file. 
- We need this fixed **now** so that the TR team has GrFN JSON to test their linking code. Can someone (@pratikbhd, @hlim1) please address this?

**Comment by hlim1** [comment]
@pauldhein `save_intermediate_files` feature was added by @adarshp,  so I might need a little help in which tester script that passes this boolean argument to `fortran_to_grfn` that MA uses. I might have missed this as we are using the `f2grfn_standalone.py`, which leaves all files, and `test_program_analysis.py` does not require any remaining files so this argument is always set to`False`, I guess. Thus, can you let me know which file you are passing `True` for `save_intermediate_files`? Then, I will have to see what is happening to debug this issue. Thanks!

**Comment by adarshp** [comment]
@pauldhein `scripts/f2grfn_standalone.py` generates the AIR JSON file (see #446). Does this resolve the issue?

**Comment by pauldhein** [comment]
@adarshp that does indeed solve my problem. Sorry that I have been out-of-the-loop!

@hlim1 thank you for responding so quickly, but it looks like we have a solution that doesn't require anything else from the PA side.
