### ISSUE TITLE
delphi depends on unreleased features from Indra

### ISSUE THREAD

**Issue by csala** [ml4ai/delphi#5]
`delphy/core.py` imports the class `Influence` from `indra.statements` module.

However, the latest indra version release, 1.5, which is the one that pip installs by default from PyPi, does not include this class, since this feature was introduced after the latest release.

I suggest the following as an interim solution:

* Update the `requirements.txt` file to point at the indra git repository instead of Pypi.
* Add `dependency_links` in `setup.py` to make it install indra using git instead of PyPi.

And, for later releases:

* Use released versions as dependencies and hold back any changes that depend on unreleased features.
* Add version specifications in `requirements.txt` and `setup.py` to avoid confusions and prevent problems due to backwards incompatible changes in any of the dependencies.

**Comment by adarshp** [comment]
Thanks for bringing this to our attention, and for your suggestions! We will fix this soon. (We welcome pull requests too!)
