### ISSUE TITLE
Implement functionality to process data from FEWSNET

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#57]
The data is contained in shape files, so we will need to figure out how to use those.

- [x] Write script to programmatically download FEWSNET data.
- [x] Write script that gets IPC phase classifications for individual South Sudan districts for different time periods.
- [x] Connect data from shapefiles that contain IPC phase classification data and the shape files that contain Administrative boundaries

**Comment by cl4yton** [comment]
Suggest bringing in Egoitz (and Steven), who is concerned with spatial context, to this discussion.

**Comment by adarshp** [comment]
Closed by  4474dec
