### ISSUE TITLE
Implement updating of ProgramAnalysisGraph nodes to be in sync with the loop index

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#58]
Right now, there is a 'delay' in the updating of nodes in a ProgramAnalysisGraph (which should be integrated better into the AnalysisGraph class) that makes it so that the 'downstream' outputs like `YIELD_EST` are updated a couple of steps after the 'upstream' outputs like `RAIN` (in the example `crop_yield.f`. This results in the `DAY` variable which serves as the loop index lagging behind by 2 compared to the FORTRAN program.

**Comment by pauldhein** [comment]
@adarshp does this task need to be updated at all given the changes made in PR #63?

**Comment by adarshp** [comment]
PR #63 is meant to close this issue.

**Comment by adarshp** [comment]
Closed by #63
