### ISSUE TITLE
Library Functions

### ISSUE THREAD

**Issue by stephensj2** [ml4ai/delphi#61]
Appropriate handlers need to be created for library functions (such as read, write, etc) in the program analysis code. It is not clear to me at this moment if it is necessary they preserve the actual behavior of fortran's libraries though. By that, I mean I don't think delphi cares about the particulars of the call. I believe it only cares that the code is receiving input or producing output. If that is the case, rather than creating handler to translate fortran library calls into python calls, it may be possible to instead replace all input calls with a single call to a function like 'input' and all output calls to a function like 'output'. The user can then define what an input and output call is.

**Comment by adarshp** [comment]
I think this is also handled now.
