### ISSUE TITLE
Putting modifications to OpenFortranParser under version control

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#82]
If we are modifying OpenFortranParser to perform program analysis, we should keep the modified source code under version control as well.

**Comment by pauldhein** [comment]
This isn't my decision to make, but my suggestion would be that we should fork the OFP repo and have that repo **not** live under delphi. We could then provide a pointer to this repo in a config file located in delphi after resolving #80.

**Comment by adarshp** [comment]
@pauldhein I agree.

@pratikbhd Please make a Github repository for the OpenFortranParser work and put a pointer to it in the README.md file in the delphi repo root.

**Comment by cl4yton** [comment]
All: I also agree.

I have created a new repo called program_analysis (https://github.com/ml4ai/program_analysis) and have created a stub directory called OpenFortranParser that we should use for any work we do on it.

@pratikbhd : Please still add a pointer in the README.md of the delphi repo root pointing to this repository.

**Comment by adarshp** [comment]
Closing this as we are not actually modifying OpenFortranParser itself.
