### ISSUE TITLE
Set up an backcasting evaluation framework for Delphi.

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#84]
- [x] Implement a function that takes the name (str) of a concept as a parameter, and the maximum depth for graph traversal (int), and returns a CAG centered around the concept.
- [x] Write a function that takes a concept-level CAG as an input parameter connects each concept of the CAG with an indicator, while ensuring that indicators are not shared among concepts.
- [x] Set initial conditions for backcasting - get mean values of indicators from relevant data sources, for South Sudan in 2016.
- [x] Run the DBN for one time step
- [x] Compare predicted values of indicators to actual values.

**Comment by cl4yton** [comment]
+1

**Comment by adarshp** [comment]
Closed by #314
